name: readme_matlab

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matlab:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: |
          echo "CC=gcc-9" >> $GITHUB_ENV
          echo "CXX=g++-9" >> $GITHUB_ENV
          VERBOSE=1 pip install --verbose -e .

      - run: cat -n readme.m

      - uses: matlab-actions/setup-matlab@v0
        with:
          release: R2022a

      - uses: matlab-actions/run-command@v0
        with:
          command: readme

